// Code generated by protoc-gen-go. DO NOT EDIT.
// source: firsttry.proto

package firsttry

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The Howdy message containing user's name
type HowdyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HowdyRequest) Reset()         { *m = HowdyRequest{} }
func (m *HowdyRequest) String() string { return proto.CompactTextString(m) }
func (*HowdyRequest) ProtoMessage()    {}
func (*HowdyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8b646d3344649d, []int{0}
}

func (m *HowdyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HowdyRequest.Unmarshal(m, b)
}
func (m *HowdyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HowdyRequest.Marshal(b, m, deterministic)
}
func (m *HowdyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HowdyRequest.Merge(m, src)
}
func (m *HowdyRequest) XXX_Size() int {
	return xxx_messageInfo_HowdyRequest.Size(m)
}
func (m *HowdyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HowdyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HowdyRequest proto.InternalMessageInfo

func (m *HowdyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The Howdy Response message containing greetings
type HowdyResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HowdyResponse) Reset()         { *m = HowdyResponse{} }
func (m *HowdyResponse) String() string { return proto.CompactTextString(m) }
func (*HowdyResponse) ProtoMessage()    {}
func (*HowdyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8b646d3344649d, []int{1}
}

func (m *HowdyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HowdyResponse.Unmarshal(m, b)
}
func (m *HowdyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HowdyResponse.Marshal(b, m, deterministic)
}
func (m *HowdyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HowdyResponse.Merge(m, src)
}
func (m *HowdyResponse) XXX_Size() int {
	return xxx_messageInfo_HowdyResponse.Size(m)
}
func (m *HowdyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HowdyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HowdyResponse proto.InternalMessageInfo

func (m *HowdyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The Random Number Request message containing base for random number generation
type RandomNoRequest struct {
	Base                 int32    `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomNoRequest) Reset()         { *m = RandomNoRequest{} }
func (m *RandomNoRequest) String() string { return proto.CompactTextString(m) }
func (*RandomNoRequest) ProtoMessage()    {}
func (*RandomNoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8b646d3344649d, []int{2}
}

func (m *RandomNoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomNoRequest.Unmarshal(m, b)
}
func (m *RandomNoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomNoRequest.Marshal(b, m, deterministic)
}
func (m *RandomNoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomNoRequest.Merge(m, src)
}
func (m *RandomNoRequest) XXX_Size() int {
	return xxx_messageInfo_RandomNoRequest.Size(m)
}
func (m *RandomNoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomNoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RandomNoRequest proto.InternalMessageInfo

func (m *RandomNoRequest) GetBase() int32 {
	if m != nil {
		return m.Base
	}
	return 0
}

// The Random Number Response message containing the random number
type RandomNoResponse struct {
	RandomNumber         int32    `protobuf:"varint,1,opt,name=randomNumber,proto3" json:"randomNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomNoResponse) Reset()         { *m = RandomNoResponse{} }
func (m *RandomNoResponse) String() string { return proto.CompactTextString(m) }
func (*RandomNoResponse) ProtoMessage()    {}
func (*RandomNoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8b646d3344649d, []int{3}
}

func (m *RandomNoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomNoResponse.Unmarshal(m, b)
}
func (m *RandomNoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomNoResponse.Marshal(b, m, deterministic)
}
func (m *RandomNoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomNoResponse.Merge(m, src)
}
func (m *RandomNoResponse) XXX_Size() int {
	return xxx_messageInfo_RandomNoResponse.Size(m)
}
func (m *RandomNoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomNoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RandomNoResponse proto.InternalMessageInfo

func (m *RandomNoResponse) GetRandomNumber() int32 {
	if m != nil {
		return m.RandomNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*HowdyRequest)(nil), "HowdyRequest")
	proto.RegisterType((*HowdyResponse)(nil), "HowdyResponse")
	proto.RegisterType((*RandomNoRequest)(nil), "RandomNoRequest")
	proto.RegisterType((*RandomNoResponse)(nil), "RandomNoResponse")
}

func init() { proto.RegisterFile("firsttry.proto", fileDescriptor_5c8b646d3344649d) }

var fileDescriptor_5c8b646d3344649d = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcb, 0x2c, 0x2a,
	0x2e, 0x29, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0xf1, 0xc8,
	0x2f, 0x4f, 0xa9, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x34, 0xb9, 0x78, 0xa1,
	0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13,
	0xd3, 0x61, 0xea, 0x60, 0x5c, 0x25, 0x55, 0x2e, 0xfe, 0xa0, 0xc4, 0xbc, 0x94, 0xfc, 0x5c, 0xbf,
	0x7c, 0x24, 0x13, 0x93, 0x12, 0x8b, 0x21, 0x2a, 0x59, 0x83, 0xc0, 0x6c, 0x25, 0x33, 0x2e, 0x01,
	0x84, 0x32, 0xa8, 0xa1, 0x4a, 0x5c, 0x3c, 0x45, 0x10, 0xb1, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0xa8,
	0x7a, 0x14, 0x31, 0xa3, 0x42, 0x2e, 0x0e, 0x37, 0x90, 0xfb, 0x43, 0x8a, 0x2a, 0x85, 0xb4, 0xb9,
	0x38, 0x82, 0x13, 0x2b, 0xc1, 0x0e, 0x13, 0xe2, 0xd5, 0x43, 0xf6, 0x84, 0x14, 0x9f, 0x1e, 0x8a,
	0x7b, 0x95, 0x18, 0x84, 0x2c, 0xb8, 0xf8, 0xdd, 0x53, 0x4b, 0x82, 0x90, 0xcc, 0x12, 0x12, 0xd0,
	0x43, 0x73, 0xa9, 0x94, 0xa0, 0x1e, 0xba, 0xa3, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xe1, 0x64, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x60, 0x16, 0x61, 0xbc, 0x39, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FirstTryClient is the client API for FirstTry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FirstTryClient interface {
	// Greeting
	SayHowdy(ctx context.Context, in *HowdyRequest, opts ...grpc.CallOption) (*HowdyResponse, error)
	// Return a random number
	GetRandomNumber(ctx context.Context, in *RandomNoRequest, opts ...grpc.CallOption) (*RandomNoResponse, error)
}

type firstTryClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstTryClient(cc grpc.ClientConnInterface) FirstTryClient {
	return &firstTryClient{cc}
}

func (c *firstTryClient) SayHowdy(ctx context.Context, in *HowdyRequest, opts ...grpc.CallOption) (*HowdyResponse, error) {
	out := new(HowdyResponse)
	err := c.cc.Invoke(ctx, "/FirstTry/SayHowdy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firstTryClient) GetRandomNumber(ctx context.Context, in *RandomNoRequest, opts ...grpc.CallOption) (*RandomNoResponse, error) {
	out := new(RandomNoResponse)
	err := c.cc.Invoke(ctx, "/FirstTry/GetRandomNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstTryServer is the server API for FirstTry service.
type FirstTryServer interface {
	// Greeting
	SayHowdy(context.Context, *HowdyRequest) (*HowdyResponse, error)
	// Return a random number
	GetRandomNumber(context.Context, *RandomNoRequest) (*RandomNoResponse, error)
}

// UnimplementedFirstTryServer can be embedded to have forward compatible implementations.
type UnimplementedFirstTryServer struct {
}

func (*UnimplementedFirstTryServer) SayHowdy(ctx context.Context, req *HowdyRequest) (*HowdyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHowdy not implemented")
}
func (*UnimplementedFirstTryServer) GetRandomNumber(ctx context.Context, req *RandomNoRequest) (*RandomNoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomNumber not implemented")
}

func RegisterFirstTryServer(s *grpc.Server, srv FirstTryServer) {
	s.RegisterService(&_FirstTry_serviceDesc, srv)
}

func _FirstTry_SayHowdy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HowdyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstTryServer).SayHowdy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FirstTry/SayHowdy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstTryServer).SayHowdy(ctx, req.(*HowdyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirstTry_GetRandomNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstTryServer).GetRandomNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FirstTry/GetRandomNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstTryServer).GetRandomNumber(ctx, req.(*RandomNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FirstTry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FirstTry",
	HandlerType: (*FirstTryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHowdy",
			Handler:    _FirstTry_SayHowdy_Handler,
		},
		{
			MethodName: "GetRandomNumber",
			Handler:    _FirstTry_GetRandomNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firsttry.proto",
}
